name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.ttokken }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Docker
          push: true
          tags: aliaksandrdub/project:${{ steps.tag_version.outputs.new_tag }}
          
      - name: Helm tool
        uses: Azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.tokken }}
          
      - name: Test manifests
        continue-on-error: true
        uses: instrumenta/kubeval-action@master
        with: 
          files: ./my_project/templates
          
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: ./Helm
          branch: main
          linting: off
          charts_url: https://.github.io/my_project/
          token: ${{ secrets.tokken}}
          app_version: ${{ steps.tag_version.outputs.new_tag }}
          chart_version: ${{ steps.tag_version.outputs.new_tag }}
